# Generated by Django 6.0.6 on 2026-08-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='pincode',
        ),
        migrations.AddField(
            model_name='users',
            name='lastname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
